var b;b||(b=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var h={},p;for(p in b)b.hasOwnProperty(p)&&(h[p]=b[p]);var v=!1,z=!1,B=!1,aa=!1;
if(b.ENVIRONMENT)if("WEB"===b.ENVIRONMENT)v=!0;else if("WORKER"===b.ENVIRONMENT)z=!0;else if("NODE"===b.ENVIRONMENT)B=!0;else if("SHELL"===b.ENVIRONMENT)aa=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else v="object"===typeof window,z="function"===typeof importScripts,B="object"===typeof process&&"function"===typeof require&&!v&&!z,aa=!v&&!B&&!z;
if(B){b.print||(b.print=console.log);b.printErr||(b.printErr=console.warn);var ba,ca;b.read=function(a,c){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(__dirname+"/"+a);var d=ba.readFileSync(a);return c?d:d.toString()};b.readBinary=function(a){a=b.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};b.load=function(a){da(read(a))};b.thisProgram||(b.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);
"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof C))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(aa)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available";},b.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=
typeof scriptArgs?b.arguments=scriptArgs:"undefined"!=typeof arguments&&(b.arguments=arguments),"function"===typeof quit&&(b.quit=function(a){quit(a)}),eval("if (typeof gc === 'function' && gc.toString().indexOf('[native code]') > 0) var gc = undefined");else if(v||z)b.read=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},z&&(b.readBinary=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),
b.readAsync=function(a,c,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)},"undefined"!=typeof arguments&&(b.arguments=arguments),"undefined"!==typeof console?(b.print||(b.print=function(a){console.log(a)}),b.printErr||(b.printErr=function(a){console.warn(a)})):b.print||(b.print=function(){}),z&&(b.load=importScripts),"undefined"===typeof b.setWindowTitle&&(b.setWindowTitle=
function(a){document.title=a});else throw"Unknown runtime environment. Where are we?";function da(a){eval.call(null,a)}!b.load&&b.read&&(b.load=function(a){da(b.read(a))});b.print||(b.print=function(){});b.printErr||(b.printErr=b.print);b.arguments||(b.arguments=[]);b.thisProgram||(b.thisProgram="./this.program");b.quit||(b.quit=function(a,c){throw c;});b.print=b.print;b.c=b.printErr;b.preRun=[];b.postRun=[];for(p in h)h.hasOwnProperty(p)&&(b[p]=h[p]);
var h=void 0,E={G:function(a){return tempRet0=a},C:function(){return tempRet0},l:function(){return D},e:function(a){D=a},t:function(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?E.g:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}},A:function(a){return Math.max(E.t(a),E.g)},H:16,X:function(a,c){"double"===c||"i64"===c?a&7&&(assert(4===(a&7)),a+=4):assert(0===
(a&3));return a},Q:function(a,c,d){return d||"i64"!=a&&"double"!=a?a?Math.min(c||(a?E.A(a):0),E.g):Math.min(c,8):8},i:function(a,c,d){return d&&d.length?b["dynCall_"+a].apply(null,[c].concat(d)):b["dynCall_"+a].call(null,c)},b:[],u:function(a){for(var c=0;c<E.b.length;c++)if(!E.b[c])return E.b[c]=a,2*(1+c);throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";},F:function(a){E.b[(a-2)/2]=null},a:function(a){E.a.k||(E.a.k={});E.a.k[a]||(E.a.k[a]=1,b.c(a))},
j:{},S:function(a,c){assert(c);E.j[c]||(E.j[c]={});var d=E.j[c];d[a]||(d[a]=1===c.length?function(){return E.i(c,a)}:2===c.length?function(d){return E.i(c,a,[d])}:function(){return E.i(c,a,Array.prototype.slice.call(arguments))});return d[a]},R:function(){throw"You must build with -s RETAIN_COMPILER_SETTINGS=1 for Runtime.getCompilerSetting or emscripten_get_compiler_setting to work";},d:function(a){var c=D;D=D+a|0;D=D+15&-16;return c},m:function(a){var c=H;H=H+a|0;H=H+15&-16;return c},r:function(a){var c=
I[K>>2];a=(c+a+15|0)&-16;I[K>>2]=a;if(a=a>=L)ea(),a=!0;return a?(I[K>>2]=c,0):c},p:function(a,c){return Math.ceil(a/(c?c:16))*(c?c:16)},W:function(a,c,d){return d?+(a>>>0)+4294967296*+(c>>>0):+(a>>>0)+4294967296*+(c|0)},f:1024,g:4,I:0};b.Runtime=E;E.addFunction=E.u;E.removeFunction=E.F;var fa=0;function assert(a,c){a||M("Assertion failed: "+c)}
function ga(a){var c=b["_"+a];if(!c)try{c=eval("_"+a)}catch(d){}assert(c,"Cannot call unknown function "+a+" (perhaps LLVM optimizations or closure removed it?)");return c}var ha,ia;
(function(){function a(a){a=a.toString().match(f).slice(1);return{arguments:a[0],body:a[1],returnValue:a[2]}}function c(){if(!k){k={};for(var c in d)d.hasOwnProperty(c)&&(k[c]=a(d[c]))}}var d={stackSave:function(){E.l()},stackRestore:function(){E.e()},arrayToC:function(a){var c=E.d(a.length);ja(a,c);return c},stringToC:function(a){var c=0;if(null!==a&&void 0!==a&&0!==a){var d=(a.length<<2)+1,c=E.d(d);ka(a,c,d)}return c}},e={string:d.stringToC,array:d.arrayToC};ia=function(a,c,d,f,k){a=ga(a);var A=
[],q=0;if(f)for(var n=0;n<f.length;n++){var y=e[d[n]];y?(0===q&&(q=E.l()),A[n]=y(f[n])):A[n]=f[n]}d=a.apply(null,A);"string"===c&&(d=la(d));if(0!==q){if(k&&k.async){EmterpreterAsync.J.push(function(){E.e(q)});return}E.e(q)}return d};var f=/^function\s*[a-zA-Z$_0-9]*\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/,k=null;ha=function(d,e,f){f=f||[];var x=ga(d);d=f.every(function(a){return"number"===a});var u="string"!==e;if(u&&d)return x;var A=f.map(function(a,c){return"$"+c});e="(function("+
A.join(",")+") {";var q=f.length;if(!d){c();e+="var stack = "+k.stackSave.body+";";for(var n=0;n<q;n++){var y=A[n],G=f[n];"number"!==G&&(G=k[G+"ToC"],e+="var "+G.arguments+" = "+y+";",e+=G.body+";",e+=y+"=("+G.returnValue+");")}}f=a(function(){return x}).returnValue;e+="var ret = "+f+"("+A.join(",")+");";u||(f=a(function(){return la}).returnValue,e+="ret = "+f+"(ret);");d||(c(),e+=k.stackRestore.body.replace("()","(stack)")+";");return eval(e+"return ret})")}})();b.ccall=ia;b.cwrap=ha;
function ma(a,c,d){d=d||"i8";"*"===d.charAt(d.length-1)&&(d="i32");switch(d){case "i1":N[a>>0]=c;break;case "i8":N[a>>0]=c;break;case "i16":O[a>>1]=c;break;case "i32":I[a>>2]=c;break;case "i64":tempI64=[c>>>0,(tempDouble=c,1<=+na(tempDouble)?0<tempDouble?(oa(+pa(tempDouble/4294967296),4294967295)|0)>>>0:~~+qa((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];I[a>>2]=tempI64[0];I[a+4>>2]=tempI64[1];break;case "float":ra[a>>2]=c;break;case "double":sa[a>>3]=c;break;default:M("invalid type for setValue: "+
d)}}b.setValue=ma;function ta(a,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":return N[a>>0];case "i8":return N[a>>0];case "i16":return O[a>>1];case "i32":return I[a>>2];case "i64":return I[a>>2];case "float":return ra[a>>2];case "double":return sa[a>>3];default:M("invalid type for setValue: "+c)}return null}b.getValue=ta;b.ALLOC_NORMAL=0;b.ALLOC_STACK=1;b.ALLOC_STATIC=2;b.ALLOC_DYNAMIC=3;b.ALLOC_NONE=4;
function P(a,c,d,e){var f,k;"number"===typeof a?(f=!0,k=a):(f=!1,k=a.length);var g="string"===typeof c?c:null,l;4==d?l=e:l=["function"===typeof Q?Q:E.m,E.d,E.m,E.r][void 0===d?2:d](Math.max(k,g?1:c.length));if(f){e=l;assert(0==(l&3));for(a=l+(k&-4);e<a;e+=4)I[e>>2]=0;for(a=l+k;e<a;)N[e++>>0]=0;return l}if("i8"===g)return a.subarray||a.slice?R.set(a,l):R.set(new Uint8Array(a),l),l;e=0;for(var r,x;e<k;)f=a[e],"function"===typeof f&&(f=E.T(f)),d=g||c[e],0===d?e++:("i64"==d&&(d="i32"),ma(l+e,f,d),x!==
d&&(r=E.t(d),x=d),e+=r);return l}b.allocate=P;b.getMemory=function(a){return ua?S?Q(a):E.r(a):E.m(a)};function la(a,c){if(0===c||!a)return"";for(var d=0,e,f=0;;){e=R[a+f>>0];d|=e;if(0==e&&!c)break;f++;if(c&&f==c)break}c||(c=f);e="";if(128>d){for(;0<c;)d=String.fromCharCode.apply(String,R.subarray(a,a+Math.min(c,1024))),e=e?e+d:d,a+=1024,c-=1024;return e}return b.UTF8ToString(a)}b.Pointer_stringify=la;b.AsciiToString=function(a){for(var c="";;){var d=N[a++>>0];if(!d)return c;c+=String.fromCharCode(d)}};
b.stringToAscii=function(a,c){return va(a,c,!1)};var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,c){for(var d=c;a[d];)++d;if(16<d-c&&a.subarray&&wa)return wa.decode(a.subarray(c,d));for(var e,f,k,g,l,r,d="";;){e=a[c++];if(!e)return d;e&128?(f=a[c++]&63,192==(e&224)?d+=String.fromCharCode((e&31)<<6|f):(k=a[c++]&63,224==(e&240)?e=(e&15)<<12|f<<6|k:(g=a[c++]&63,240==(e&248)?e=(e&7)<<18|f<<12|k<<6|g:(l=a[c++]&63,248==(e&252)?e=(e&3)<<24|f<<18|k<<12|g<<6|l:(r=a[c++]&63,e=(e&1)<<30|f<<24|k<<18|g<<12|l<<6|r))),65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023)))):d+=String.fromCharCode(e)}}b.UTF8ArrayToString=xa;b.UTF8ToString=function(a){return xa(R,a)};
function ya(a,c,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);55296<=g&&57343>=g&&(g=65536+((g&1023)<<10)|a.charCodeAt(++k)&1023);if(127>=g){if(d>=e)break;c[d++]=g}else{if(2047>=g){if(d+1>=e)break;c[d++]=192|g>>6}else{if(65535>=g){if(d+2>=e)break;c[d++]=224|g>>12}else{if(2097151>=g){if(d+3>=e)break;c[d++]=240|g>>18}else{if(67108863>=g){if(d+4>=e)break;c[d++]=248|g>>24}else{if(d+5>=e)break;c[d++]=252|g>>30;c[d++]=128|g>>24&63}c[d++]=128|g>>18&63}c[d++]=128|
g>>12&63}c[d++]=128|g>>6&63}c[d++]=128|g&63}}c[d]=0;return d-f}b.stringToUTF8Array=ya;function ka(a,c,d){return ya(a,R,c,d)}b.stringToUTF8=ka;function Aa(a){for(var c=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:2097151>=e?c+4:67108863>=e?c+5:c+6}return c}b.lengthBytesUTF8=Aa;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function Ba(a){return a.replace(/__Z[\w\d_]+/g,function(a){var d;a:{var e=b.___cxa_demangle||b.__cxa_demangle;if(e)try{var f=a.substr(1),k=Aa(f)+1,g=Q(k);ka(f,g,k);var l=Q(4),r=e(g,0,0,l);if(0===ta(l,"i32")&&r){d=la(r);break a}}catch(x){}finally{g&&Ca(g),l&&Ca(l),r&&Ca(r)}else E.a("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");d=a}return a===d?a:a+" ["+d+"]"})}
function Da(){var a;a:{a=Error();if(!a.stack){try{throw Error(0);}catch(c){a=c}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}b.extraStackTrace&&(a+="\n"+b.extraStackTrace());return Ba(a)}b.stackTrace=Da;var buffer,N,R,O,Ea,I,Fa,ra,sa;
function Ga(){b.HEAP8=N=new Int8Array(buffer);b.HEAP16=O=new Int16Array(buffer);b.HEAP32=I=new Int32Array(buffer);b.HEAPU8=R=new Uint8Array(buffer);b.HEAPU16=Ea=new Uint16Array(buffer);b.HEAPU32=Fa=new Uint32Array(buffer);b.HEAPF32=ra=new Float32Array(buffer);b.HEAPF64=sa=new Float64Array(buffer)}var Ha,H,ua,Ia,D,Ja,Ka,K;Ha=H=Ia=D=Ja=Ka=K=0;ua=!1;
function ea(){M("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+L+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var La=b.TOTAL_STACK||5242880,L=b.TOTAL_MEMORY||16777216;L<La&&b.c("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+L+"! (TOTAL_STACK="+La+")");
b.buffer?buffer=b.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(b.wasmMemory=new WebAssembly.Memory({initial:L/65536,maximum:L/65536}),buffer=b.wasmMemory.buffer):buffer=new ArrayBuffer(L);Ga();I[0]=1668509029;O[1]=25459;if(115!==R[2]||99!==R[3])throw"Runtime error: expected the system to be little-endian!";b.HEAP=void 0;b.buffer=buffer;b.HEAP8=N;b.HEAP16=O;b.HEAP32=I;b.HEAPU8=R;b.HEAPU16=Ea;b.HEAPU32=Fa;b.HEAPF32=ra;b.HEAPF64=sa;
function T(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c();else{var d=c.P;"number"===typeof d?void 0===c.h?b.dynCall_v(d):b.dynCall_vi(d,c.h):d(void 0===c.h?null:c.h)}}}var Ma=[],Na=[],Oa=[],Pa=[],Qa=[],S=!1;function Ra(a){Ma.unshift(a)}b.addOnPreRun=Ra;b.addOnInit=function(a){Na.unshift(a)};b.addOnPreMain=function(a){Oa.unshift(a)};b.addOnExit=function(a){Pa.unshift(a)};function Sa(a){Qa.unshift(a)}b.addOnPostRun=Sa;
function Ta(a,c,d){d=Array(0<d?d:Aa(a)+1);a=ya(a,d,0,d.length);c&&(d.length=a);return d}b.intArrayFromString=Ta;b.intArrayToString=function(a){for(var c=[],d=0;d<a.length;d++){var e=a[d];255<e&&(e&=255);c.push(String.fromCharCode(e))}return c.join("")};b.writeStringToMemory=function(a,c,d){E.a("writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!");var e,f;d&&(f=c+Aa(a),e=N[f]);ka(a,c,Infinity);d&&(N[f]=e)};function ja(a,c){N.set(a,c)}b.writeArrayToMemory=ja;
function va(a,c,d){for(var e=0;e<a.length;++e)N[c++>>0]=a.charCodeAt(e);d||(N[c>>0]=0)}b.writeAsciiToMemory=va;Math.imul&&-5===Math.imul(4294967295,5)||(Math.imul=function(a,c){var d=a&65535,e=c&65535;return d*e+((a>>>16)*e+d*(c>>>16)<<16)|0});Math.U=Math.imul;if(!Math.fround){var Ua=new Float32Array(1);Math.fround=function(a){Ua[0]=a;return Ua[0]}}Math.O=Math.fround;Math.clz32||(Math.clz32=function(a){a=a>>>0;for(var c=0;32>c;c++)if(a&1<<31-c)return c;return 32});Math.L=Math.clz32;
Math.trunc||(Math.trunc=function(a){return 0>a?Math.ceil(a):Math.floor(a)});Math.trunc=Math.trunc;var na=Math.abs,qa=Math.ceil,pa=Math.floor,oa=Math.min,U=0,Va=null,V=null;function Wa(){U++;b.monitorRunDependencies&&b.monitorRunDependencies(U)}b.addRunDependency=Wa;function Xa(){U--;b.monitorRunDependencies&&b.monitorRunDependencies(U);if(0==U&&(null!==Va&&(clearInterval(Va),Va=null),V)){var a=V;V=null;a()}}b.removeRunDependency=Xa;b.preloadedImages={};b.preloadedAudios={};var W=null;
(function(a){function c(c){var d=a.usingWasm?65536:16777216;0<c%d&&(c+=d-c%d);var d=a.buffer,e=d.byteLength;if(a.usingWasm)try{return-1!==a.wasmMemory.grow((c-e)/65536)?a.buffer=a.wasmMemory.buffer:null}catch(f){return null}else return n.__growWasmMemory((c-e)/65536),a.buffer!==d?a.buffer:null}function d(a,c){var d=q;if(0>a.indexOf("."))d=(d||{})[a];else var e=a.split("."),d=(d||{})[e[0]],d=(d||{})[e[1]];c&&(d=(d||{})[c]);void 0===d&&M("bad lookupImport to ("+a+")."+c);return d}function e(c){var d=
a.buffer;c.byteLength<d.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");var d=new Int8Array(d),e=new Int8Array(c);W||d.set(e.subarray(a.STATIC_BASE,a.STATIC_BASE+a.STATIC_BUMP),a.STATIC_BASE);e.set(d);b.buffer=buffer=c;Ga()}function f(){var c;if(a.wasmBinary)c=a.wasmBinary,c=new Uint8Array(c);else if(a.readBinary)c=a.readBinary(u);else throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";
return c}function k(){if(!a.wasmBinary&&"function"===typeof fetch){var c=document.currentScript.src.split("/").slice(0,-1).join("/");return fetch(c+"/"+u,{M:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+u+"'";return a.arrayBuffer()})}return new Promise(function(a){a(f())})}function g(c,d,e){if("function"!==typeof a.asm||a.asm===cb)a.asmPreload?a.asm=a.asmPreload:eval(a.read(A));return"function"!==typeof a.asm?(a.printErr("asm evalling did not set the module properly"),
!1):a.asm(c,d,e)}function l(c,d){function f(c){n=c.exports;n.memory&&e(n.memory);a.asm=n;a.usingWasm=!0;Xa()}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;d.memory=a.wasmMemory;q.global={NaN:NaN,Infinity:Infinity};q["global.Math"]=c.Math;q.env=d;Wa();if(a.instantiateWasm)try{return a.instantiateWasm(q,f)}catch(g){return a.printErr("Module.instantiateWasm callback failed with error: "+
g),!1}k().then(function(a){return WebAssembly.instantiate(a,q)}).then(function(a){f(a.instance)}).catch(function(c){a.printErr("failed to asynchronously prepare wasm: "+c);a.quit(1,c)});return{}}var r=a.wasmJSMethod||"native-wasm";a.wasmJSMethod=r;var x=a.wasmTextFile||"supercop.wast",u=a.wasmBinaryFile||"supercop.wasm",A=a.asmjsCodeFile||"supercop.temp.asm.js";"function"===typeof a.locateFile&&(x=a.locateFile(x),u=a.locateFile(u),A=a.locateFile(A));var q={global:null,env:null,asm2wasm:{"f64-rem":function(a,
c){return a%c},"f64-to-int":function(a){return a|0},"i32s-div":function(a,c){return(a|0)/(c|0)|0},"i32u-div":function(a,c){return(a>>>0)/(c>>>0)>>>0},"i32s-rem":function(a,c){return(a|0)%(c|0)|0},"i32u-rem":function(a,c){return(a>>>0)%(c>>>0)>>>0},"debugger":function(){debugger}},parent:a},n=null;a.asmPreload=a.asm;var y=a.reallocBuffer;a.reallocBuffer=function(a){return"asmjs"===G?y(a):c(a)};var G="";a.asm=function(c,k,u){if(!k.table){var J=a.wasmTableSize;void 0===J&&(J=1024);var y=a.wasmMaxTableSize;
k.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==y?new WebAssembly.Table({initial:J,maximum:y,element:"anyfunc"}):new WebAssembly.Table({initial:J,element:"anyfunc"}):Array(J);a.wasmTable=k.table}k.memoryBase||(k.memoryBase=a.STATIC_BASE);k.tableBase||(k.tableBase=0);for(var m,J=r.split(","),y=0;y<J.length;y++)if(G=m=J[y],"native-wasm"===m){if(m=l(c,k))break}else if("asmjs"===m){if(m=g(c,k,u))break}else if("interpret-asm2wasm"===m||"interpret-s-expr"===m||"interpret-binary"===
m){var F=c,w=k,za=u;if("function"!==typeof WasmJS)a.printErr("WasmJS not detected - polyfill not bundled?"),m=!1;else{var t=WasmJS({});t.outside=a;t.info=q;t.lookupImport=d;assert(za===a.buffer);q.global=F;q.env=w;assert(za===a.buffer);w.memory=za;assert(w.memory instanceof ArrayBuffer);t.providedTotalMemory=a.buffer.byteLength;F=void 0;F="interpret-binary"===m?f():a.read("interpret-asm2wasm"==m?A:x);w=void 0;if("interpret-asm2wasm"==m)w=t._malloc(F.length+1),t.writeAsciiToMemory(F,w),t._load_asm2wasm(w);
else if("interpret-s-expr"===m)w=t._malloc(F.length+1),t.writeAsciiToMemory(F,w),t._load_s_expr2wasm(w);else if("interpret-binary"===m)w=t._malloc(F.length),t.HEAPU8.set(F,w),t._load_binary2wasm(w,F.length);else throw"what? "+m;t._free(w);t._instantiate(w);a.newBuffer&&(e(a.newBuffer),a.newBuffer=null);m=n=t.asmExports}if(m)break}else throw"bad method: "+m;if(!m)throw"no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods";
return m};var cb=a.asm})(b);Ha=E.f;H=Ha+35456;Na.push();W=0<=b.wasmJSMethod.indexOf("asmjs")||0<=b.wasmJSMethod.indexOf("interpret-asm2wasm")?"supercop.js.mem":null;b.STATIC_BASE=Ha;b.STATIC_BUMP=35456;var Ya=H;H+=16;b._sbrk=Za;b._memset=$a;b._memcpy=ab;var X=0;function Y(){X+=4;return I[X-4>>2]}var bb={};
function Z(a,c){X=c;try{var d=Y(),e=Y(),f=Y(),k=0;Z.buffer||(Z.o=[null,[],[]],Z.q=function(a,c){var d=Z.o[a];assert(d);0===c||10===c?((1===a?b.print:b.printErr)(xa(d,0)),d.length=0):d.push(c)});for(var g=0;g<f;g++){for(var l=I[e+8*g>>2],r=I[e+(8*g+4)>>2],x=0;x<r;x++)Z.q(d,R[l+x]);k+=r}return k}catch(u){return"undefined"!==typeof FS&&u instanceof FS.n||M(u),-u.s}}Pa.push(function(){var a=b._fflush;a&&a(0);if(a=Z.q){var c=Z.o;c[1].length&&a(1,10);c[2].length&&a(2,10)}});K=P(1,"i32",2);Ia=D=E.p(H);
Ja=Ia+La;Ka=E.p(Ja);I[K>>2]=Ka;ua=!0;b.wasmTableSize=6;b.wasmMaxTableSize=6;b.v={Math:Math,Int8Array:Int8Array,Int16Array:Int16Array,Int32Array:Int32Array,Uint8Array:Uint8Array,Uint16Array:Uint16Array,Uint32Array:Uint32Array,Float32Array:Float32Array,Float64Array:Float64Array,NaN:NaN,Infinity:Infinity};
b.w={abort:M,assert:assert,enlargeMemory:function(){ea()},getTotalMemory:function(){return L},abortOnCannotGrowMemory:ea,invoke_ii:function(a,c){try{return b.dynCall_ii(a,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;b.setThrew(1,0)}},invoke_iiii:function(a,c,d,e){try{return b.dynCall_iiii(a,c,d,e)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;b.setThrew(1,0)}},___lock:function(){},___syscall6:function(a,c){X=c;try{var d=bb.B();FS.close(d);return 0}catch(e){return"undefined"!==
typeof FS&&e instanceof FS.n||M(e),-e.s}},___setErrNo:function(a){b.___errno_location&&(I[b.___errno_location()>>2]=a);return a},_abort:function(){b.abort()},___syscall140:function(a,c){X=c;try{var d=bb.B();Y();var e=Y(),f=Y(),k=Y();FS.V(d,e,k);I[f>>2]=d.position;d.D&&0===e&&0===k&&(d.D=null);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.n||M(g),-g.s}},_emscripten_memcpy_big:function(a,c,d){R.set(R.subarray(c,c+d),a);return a},___syscall54:function(a,c){X=c;return 0},___unlock:function(){},
___syscall146:Z,DYNAMICTOP_PTR:K,tempDoublePtr:Ya,ABORT:fa,STACKTOP:D,STACK_MAX:Ja};var db=b.asm(b.v,b.w,buffer);b.asm=db;b._create_keypair=function(){return b.asm._create_keypair.apply(null,arguments)};b._sign=function(){return b.asm._sign.apply(null,arguments)};b.getTempRet0=function(){return b.asm.getTempRet0.apply(null,arguments)};b._verify=function(){return b.asm._verify.apply(null,arguments)};b._fflush=function(){return b.asm._fflush.apply(null,arguments)};
b.runPostSets=function(){return b.asm.runPostSets.apply(null,arguments)};b.setTempRet0=function(){return b.asm.setTempRet0.apply(null,arguments)};b.establishStackSpace=function(){return b.asm.establishStackSpace.apply(null,arguments)};b.stackSave=function(){return b.asm.stackSave.apply(null,arguments)};var $a=b._memset=function(){return b.asm._memset.apply(null,arguments)},Q=b._malloc=function(){return b.asm._malloc.apply(null,arguments)};
b._emscripten_get_global_libc=function(){return b.asm._emscripten_get_global_libc.apply(null,arguments)};var ab=b._memcpy=function(){return b.asm._memcpy.apply(null,arguments)};b.stackAlloc=function(){return b.asm.stackAlloc.apply(null,arguments)};b.setThrew=function(){return b.asm.setThrew.apply(null,arguments)};var Za=b._sbrk=function(){return b.asm._sbrk.apply(null,arguments)},Ca=b._free=function(){return b.asm._free.apply(null,arguments)};
b.stackRestore=function(){return b.asm.stackRestore.apply(null,arguments)};b.___errno_location=function(){return b.asm.___errno_location.apply(null,arguments)};b.dynCall_ii=function(){return b.asm.dynCall_ii.apply(null,arguments)};b.dynCall_iiii=function(){return b.asm.dynCall_iiii.apply(null,arguments)};E.d=b.stackAlloc;E.l=b.stackSave;E.e=b.stackRestore;E.N=b.establishStackSpace;E.G=b.setTempRet0;E.C=b.getTempRet0;b.asm=db;
if(W)if("function"===typeof b.locateFile?W=b.locateFile(W):b.memoryInitializerPrefixURL&&(W=b.memoryInitializerPrefixURL+W),B||aa){var eb=b.readBinary(W);R.set(eb,E.f)}else{var gb=function(){b.readAsync(W,fb,function(){throw"could not load memory initializer "+W;})};Wa();var fb=function(a){a.byteLength&&(a=new Uint8Array(a));R.set(a,E.f);b.memoryInitializerRequest&&delete b.memoryInitializerRequest.response;Xa()};if(b.memoryInitializerRequest){var hb=function(){var a=b.memoryInitializerRequest;200!==
a.status&&0!==a.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+a.status+", retrying "+W),gb()):fb(a.response)};b.memoryInitializerRequest.response?setTimeout(hb,0):b.memoryInitializerRequest.addEventListener("load",hb)}else gb()}function C(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}C.prototype=Error();C.prototype.constructor=C;var ib=null,V=function jb(){b.calledRun||kb();b.calledRun||(V=jb)};
b.callMain=b.K=function(a){function c(){for(var a=0;3>a;a++)e.push(0)}a=a||[];S||(S=!0,T(Na));var d=a.length+1,e=[P(Ta(b.thisProgram),"i8",0)];c();for(var f=0;f<d-1;f+=1)e.push(P(Ta(a[f]),"i8",0)),c();e.push(0);e=P(e,"i32",0);try{var k=b._main(d,e,0);lb(k,!0)}catch(g){g instanceof C||("SimulateInfiniteLoop"==g?b.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),b.c("exception thrown: "+a),b.quit(1,g)))}finally{}};
function kb(a){function c(){if(!b.calledRun&&(b.calledRun=!0,!fa)){S||(S=!0,T(Na));T(Oa);if(b.onRuntimeInitialized)b.onRuntimeInitialized();b._main&&mb&&b.callMain(a);if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;)Sa(b.postRun.shift());T(Qa)}}a=a||b.arguments;null===ib&&(ib=Date.now());if(!(0<U)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)Ra(b.preRun.shift());T(Ma);0<U||b.calledRun||(b.setStatus?(b.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){b.setStatus("")},1);c()},1)):c())}}b.run=b.run=kb;function lb(a,c){if(!c||!b.noExitRuntime){if(!b.noExitRuntime&&(fa=!0,D=void 0,T(Pa),b.onExit))b.onExit(a);B&&process.exit(a);b.quit(a,new C(a))}}b.exit=b.exit=lb;var nb=[];
function M(a){void 0!==a?(b.print(a),b.c(a),a=JSON.stringify(a)):a="";fa=!0;var c="abort("+a+") at "+Da()+"\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.";nb&&nb.forEach(function(d){c=d(c,a)});throw c;}b.abort=b.abort=M;if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();var mb=!0;b.noInitialRun&&(mb=!1);kb();
